name: Example action
inputs:
  message: 
    description: "uma mensagem simples"
    default: "Hello Action!"
    type: string

runs:
  using: composite
  steps:
  
    - run: echo "${{ inputs.message }}"
      shell: bash

    - run: echo "${{ env.message }}"
      shell: bash
      
    - id: output-step
      run: echo "result='Hello Outputs'" >> $GITHUB_OUTPUT
      shell: bash
    
    - run: echo "${{ steps.output-step.outputs.result }}"
      shell: bash
