name: Example action
inputs:
  message: 
    description: "uma mensagem simples"
    default: "Hello Action!"
    type: string

runs:
  using: composite
  steps:
  
    - run: echo "${{ inputs.message }}"
      shell: bash
